import { defineConfig } from "vite";

/** Static Stayli clone — index.html is generated by scripts/process-stayli.mjs */
export default defineConfig({
  build: {
    outDir: "dist",
    rollupOptions: {
      input: "index.html",
    },
  },
});
